title: About A Girl
author: Ana Đorđević
description: A personal blog of random musings.
site_url: https://ana.dj
timezone: Australia/Melbourne

sources:
  pages: pages
  posts: posts

social:
  mail: mail@ana.dj
  twitter: anakinakova
  github: anakinakova
  lastfm: jezemabel
  instagram: jezemabel
